//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication4.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capacite.
        /// </summary>
        public static string capacite {
            get {
                return ResourceManager.GetString("capacite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categorie.
        /// </summary>
        public static string categorie {
            get {
                return ResourceManager.GetString("categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chercher.
        /// </summary>
        public static string chercher {
            get {
                return ResourceManager.GetString("chercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir Categorie.
        /// </summary>
        public static string choixCat {
            get {
                return ResourceManager.GetString("choixCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir Marque.
        /// </summary>
        public static string choixMar {
            get {
                return ResourceManager.GetString("choixMar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue Chez Nous ....
        /// </summary>
        public static string maptitre {
            get {
                return ResourceManager.GetString("maptitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La vitesse max.
        /// </summary>
        public static string max_v {
            get {
                return ResourceManager.GetString("max-v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherchez sur des centaines de sites et louez un véhicule au MAROC.
        /// </summary>
        public static string Soustitre {
            get {
                return ResourceManager.GetString("Soustitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location de voitures au MAROC.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les voitures les moins cher.
        /// </summary>
        public static string titrecats {
            get {
                return ResourceManager.GetString("titrecats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualiser.
        /// </summary>
        public static string visualiser {
            get {
                return ResourceManager.GetString("visualiser", resourceCulture);
            }
        }
    }
}
