//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Voiture_info {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Voiture_info() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication4.Resources.Views.Home.Voiture-info", typeof(Voiture_info).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capacite.
        /// </summary>
        public static string capacite {
            get {
                return ResourceManager.GetString("capacite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categorie.
        /// </summary>
        public static string categorie {
            get {
                return ResourceManager.GetString("categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jour.
        /// </summary>
        public static string jour {
            get {
                return ResourceManager.GetString("jour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La vitesse maximale.
        /// </summary>
        public static string max_v {
            get {
                return ResourceManager.GetString("max-v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserver.
        /// </summary>
        public static string Reserver {
            get {
                return ResourceManager.GetString("Reserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string retour {
            get {
                return ResourceManager.GetString("retour", resourceCulture);
            }
        }
    }
}
