//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDbEntities5 : DbContext
    {
        public MyDbEntities5()
            : base("name=MyDbEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Marque> Marques { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Propretaire> Propretaires { get; set; }
        public virtual DbSet<PropretaireType> PropretaireTypes { get; set; }
        public virtual DbSet<Voiture> Voitures { get; set; }
    }
}
