//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voiture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voiture()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }
        public string imma { get; set; }
        public Nullable<int> capacite { get; set; }
        public Nullable<decimal> charge_diesl { get; set; }
        public Nullable<decimal> kilometrage { get; set; }
        public Nullable<decimal> max_vitesse { get; set; }
        public Nullable<decimal> montant { get; set; }
        public Nullable<int> Marque { get; set; }
        public Nullable<int> Module { get; set; }
        public Nullable<int> Propretaire { get; set; }
        public Nullable<int> Categorie { get; set; }
        public Nullable<bool> GPS { get; set; }
        public string imageLocation { get; set; }
    
        public virtual Categorie Categorie1 { get; set; }
        public virtual Marque Marque1 { get; set; }
        public virtual Module Module1 { get; set; }
        public virtual Propretaire Propretaire1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
